name: Reviewdog

on:
  pull_request:
    branches-ignore:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

      - name: Run rubocop
        run: bundle exec rubocop | reviewdog -reporter=github-pr-review -f=rubocop
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
