name: reviewdog

on: [pull_request]      

permissions:
  contents: read
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        id: ruby
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: install bundler
        run: gem install bundler -v 2.0.1
      - name: Bundle install
        run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - uses: reviewdog/action-setup@v1
      - name: Run rubocop
        run: bundle exec rubocop | reviewdog -reporter=github-pr-review -f=rubocop
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
